// generated by Fast Light User Interface Designer (fluid) version 1.0304

#ifndef gui_h
#define gui_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Button.H>

class GUI {
public:
  GUI();
  Fl_Double_Window *uiw;
private:
  inline void cb_Run_i(Fl_Button*, void*);
  static void cb_Run(Fl_Button*, void*);
  inline void cb_Run1_i(Fl_Button*, void*);
  static void cb_Run1(Fl_Button*, void*);
  inline void cb_Run2_i(Fl_Button*, void*);
  static void cb_Run2(Fl_Button*, void*);
  inline void cb_Run3_i(Fl_Button*, void*);
  static void cb_Run3(Fl_Button*, void*);
public:
  void show();
  void RunInvis_cb();
  void RunShadows_cb();
  void RunProjector_cb();
  void RunReflections_cb();
};
#endif
